# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: jdx/mise-action@v2
    - name: Setup host app using tuist
      run: sh generate_project.sh
      working-directory: ./HostApp
    - name: Run tests for iOS
      run: sh test_project.sh 'platform=iOS Simulator,name=Any iOS Simulator Device'
      working-directory: ./HostApp
